modules:
    weather: True
    time: True
    train: True
    roster: False
    music: False
    fealings: False
    riddle: False

wit_ai_token: VFE6BB6YN52KM6OKAHHN3SKQETGS53YS

name: LISA

meaning: Lokaal Interactive Service Android

makers: Mark en Ivar

location: Beverwijk