modules:
    weather: True
    time: True
    train: True
    music: False
    fealings: False
    riddle: False
    food: True
    toilet: True

wit_ai_token: VFE6BB6YN52KM6OKAHHN3SKQETGS53YS
ns_api_key: 9zMZBc_mLFpII0OMTQct-OMPtf93EEvammhfuDUzQMfLG-NSE1QFDw

name: LISA
meaning: Locale Interactive Service Android

makers: Mark en Ivar

location: Beverwijk