modules:
    weather: False
    time: False
    train: False
    music: False
    fealings: False
    riddle: False

wit_ai_token: VFE6BB6YN52KM6OKAHHN3SKQETGS53YS
ns_api_key: 9zMZBc_mLFpII0OMTQct-OMPtf93EEvammhfuDUzQMfLG-NSE1QFDw

name: LISA
meaning: Lokaal Interactive Service Android

makers: Mark en Ivar

location: Alkmaar