modules:
    weather: False
    time: True
    train: False
    roster: False
    music: False
    fealings: False
    riddle: True

wit_ai_token: VFE6BB6YN52KM6OKAHHN3SKQETGS53YS

name: LISA

makers: Mark en Ivar