modules:
    weather: True
    time: True
    roster: True
    train: True
    music: True
    fealings: True
    riddle: True

wit_ai_token: VFE6BB6YN52KM6OKAHHN3SKQETGS53YS

name: LISA

makers: Mark en Ivar